spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.139.203.16:3306/user_center
    username: cjj
    password: cjj72812011
  session:
    timeout: 86400
server:
  address: 0.0.0.0
